<a href="https://colab.research.google.com/github/An1ndya/IIT-Kharagpur/blob/main/Keras_sequential_embedding_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=['the glass of water',
'the glass of juice',
'the cup of tea',
'I am a good student',
'I am a good developer',
'I understand the meaning of embedding',
'Your classes are good']

In [3]:
sent

['the glass of water',
 'the glass of juice',
 'the cup of tea',
 'I am a good student',
 'I am a good developer',
 'I understand the meaning of embedding',
 'Your classes are good']

In [4]:
### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[5137, 5063, 3347, 9491], [5137, 5063, 3347, 6972], [5137, 4105, 3347, 54], [104, 4474, 4452, 7962, 411], [104, 4474, 4452, 7962, 4197], [104, 5528, 5137, 475, 3347, 9020], [5999, 8288, 5689, 7962]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5137 5063 3347 9491]
 [   0    0    0    0 5137 5063 3347 6972]
 [   0    0    0    0 5137 4105 3347   54]
 [   0    0    0  104 4474 4452 7962  411]
 [   0    0    0  104 4474 4452 7962 4197]
 [   0    0  104 5528 5137  475 3347 9020]
 [   0    0    0    0 5999 8288 5689 7962]]


In [8]:
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 218ms/step
[[[-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678
    0.04666683 -0.0447427  -0.00916139  0.00923368 -0.03961866]
  [-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678
    0.04666683 -0.0447427  -0.00916139  0.00923368 -0.03961866]
  [-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678
    0.04666683 -0.0447427  -0.00916139  0.00923368 -0.03961866]
  [-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678
    0.04666683 -0.0447427  -0.00916139  0.00923368 -0.03961866]
  [-0.01433054  0.01490949 -0.03568851 -0.00508807 -0.00108014
   -0.03681754 -0.04617016 -0.03653353  0.03752664 -0.00689814]
  [ 0.01955781  0.02425549 -0.02674007 -0.03037329 -0.04344579
    0.03775949 -0.00536501 -0.03048997  0.01134389 -0.03613459]
  [ 0.03689093 -0.00830133  0.01947996  0.00573913  0.00259107
   -0.03744341 -0.0419867  -0.0311926  -0.03389192  0.00366107]
  [ 0.0417868  -0.00454096 -0.00400316  0.02562923 -0.0347

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 5137, 5063, 3347, 9491], dtype=int32)

In [13]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 21ms/step
[[-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678  0.04666683
  -0.0447427  -0.00916139  0.00923368 -0.03961866]
 [-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678  0.04666683
  -0.0447427  -0.00916139  0.00923368 -0.03961866]
 [-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678  0.04666683
  -0.0447427  -0.00916139  0.00923368 -0.03961866]
 [-0.0055706   0.0275928  -0.01304315 -0.03768816 -0.04408678  0.04666683
  -0.0447427  -0.00916139  0.00923368 -0.03961866]
 [-0.01433054  0.01490949 -0.03568851 -0.00508807 -0.00108014 -0.03681754
  -0.04617016 -0.03653353  0.03752664 -0.00689814]
 [ 0.01955781  0.02425549 -0.02674007 -0.03037329 -0.04344579  0.03775949
  -0.00536501 -0.03048997  0.01134389 -0.03613459]
 [ 0.03689093 -0.00830133  0.01947996  0.00573913  0.00259107 -0.03744341
  -0.0419867  -0.0311926  -0.03389192  0.00366107]
 [ 0.0417868  -0.00454096 -0.00400316  0.02562923 -0.03473648 -0.0152828
